# Generated by Django 6.0.1 on 2026-01-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openproject_id', models.IntegerField()),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openproject_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('derivedStartDate', models.DateTimeField(blank=True, null=True)),
                ('derivedDueDate', models.DateTimeField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('spentTime', models.CharField(blank=True, max_length=255, null=True)),
                ('estimatedTime', models.CharField(blank=True, max_length=255, null=True)),
                ('derivedEstimatedTime', models.CharField(blank=True, max_length=255, null=True)),
                ('derivedRemainingTime', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('laborCosts', models.CharField(blank=True, max_length=255, null=True)),
                ('materialCosts', models.CharField(blank=True, max_length=255, null=True)),
                ('overallCosts', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduleManually', models.BooleanField(default=False)),
                ('ignoreNonWorkingDays', models.BooleanField(default=False)),
                ('percentageDone', models.IntegerField(blank=True, null=True)),
                ('derivedPercentageDone', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openproject_sync.project')),
            ],
            options={
                'verbose_name_plural': 'Work Packages',
                'ordering': ('subject',),
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openproject_id', models.IntegerField()),
                ('ongoing', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('spentOn', models.DateField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openproject_sync.workpackage')),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'ordering': ('work_package', 'spentOn'),
            },
        ),
    ]
