# Generated by Django 6.0.1 on 2026-01-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openproject_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('derive_start_date', models.DateField(blank=True, null=True)),
                ('derive_due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('spent_time', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('labor_costs', models.CharField(blank=True, max_length=255, null=True)),
                ('material_costs', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_costs', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openproject_id', models.IntegerField()),
                ('project', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('derivedEstimatedTime', models.CharField(blank=True, max_length=255, null=True)),
                ('derivedRemainingTime', models.CharField(blank=True, max_length=255, null=True)),
                ('ignoreNonWorkingDays', models.BooleanField(default=False)),
                ('scheduleManually', models.BooleanField(default=False)),
                ('percentageDone', models.FloatField(default=0)),
                ('derivedPercentageDone', models.FloatField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('spentTime', models.CharField(blank=True, max_length=255, null=True)),
                ('estimatedTime', models.CharField(blank=True, max_length=255, null=True)),
                ('laborCosts', models.CharField(blank=True, max_length=255, null=True)),
                ('materialCosts', models.CharField(blank=True, max_length=255, null=True)),
                ('overallCosts', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openproject_sync.workpackage')),
            ],
        ),
    ]
